module ElasticGraph
  class GraphQL
    class Client
      attr_reader name: ::String
      attr_reader source_description: ::String
      attr_reader extra_opaque_id_parts: ::Array[::String]
      def initialize: (source_description: ::String, name: ::String, ?extra_opaque_id_parts: ::Array[::String]) -> void
      def with: (?source_description: ::String, ?name: ::String, ?extra_opaque_id_parts: ::Array[::String]) -> Client

      def self.new:
        (source_description: ::String, name: ::String, ?extra_opaque_id_parts: ::Array[::String]) -> instance
      | (::String, ::String, ?::Array[::String]) -> instance

      ANONYMOUS: Client
      ELASTICGRAPH_INTERNAL: Client

      def description: () -> ::String

      interface _Resolver
        def initialize: (::Hash[::String, untyped]) -> void
        def resolve: (HTTPRequest) -> (Client | HTTPResponse)
      end

      class DefaultResolver
        include _Resolver
      end
    end
  end
end
