module ElasticGraph
  class GraphQL
    class Schema
      # Note: this is a partial signature definition (`type.rb` is ignored in `Steepfile`)
      class Type
        attr_reader name: ::String
        attr_reader fields_by_name: ::Hash[::String, Field]
        attr_reader elasticgraph_category: SchemaArtifacts::RuntimeMetadata::elasticGraphCategory?
        attr_reader graphql_type: ::GraphQL::Schema::_Type
        attr_reader grouping_missing_value_placeholder: ::String? | ::Numeric?
        def search_index_definitions: () -> ::Array[DatastoreCore::_IndexDefinition]
        def source_type: () -> Type?
        def subtypes: () -> ::Set[Type]
        def concrete_non_subtypes_in_shared_index: () -> ::Set[Type]
        def unwrap_fully: () -> Type
        def field_named: (::String) -> Field
        def fields_by_name_in_index: () -> ::Hash[::String, ::Array[Field]]
        def object?: () -> bool
        def collection?: () -> bool
        def relay_connection?: () -> bool
        def abstract?: () -> bool
        def enum?: () -> bool
        def embedded_object?: () -> bool
        def indexed_document?: () -> bool
        def indexed_aggregation?: () -> bool
        def enum_value_named: (::String) -> EnumValue
      end
    end
  end
end
