module ElasticGraph
  class GraphQL
    module Resolvers
      class QuerySource < ::GraphQL::Dataloader::Source
        def initialize: (DatastoreSearchRouter, QueryDetailsTracker, ?::Array[::String]) -> void
        @datastore_router: DatastoreSearchRouter
        @query_tracker: QueryDetailsTracker
        @opaque_id_parts: ::Array[::String]
        def fetch: (::Array[DatastoreQuery]) -> ::Array[DatastoreResponse::SearchResponse]

        def self.execute_many: (
          ::Array[DatastoreQuery],
          for_context: ::GraphQL::Query::Context
        ) -> ::Hash[DatastoreQuery, DatastoreResponse::SearchResponse]

        def self.execute_one: (
          DatastoreQuery,
          for_context: ::GraphQL::Query::Context
        ) -> DatastoreResponse::SearchResponse

        def self.datastore_opaque_id_parts_for: (::GraphQL::Query::Context) -> ::Array[::String]
      end
    end
  end
end
